# Generated by Django 2.2 on 2019-06-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('email_address', models.CharField(max_length=100)),
                ('input_reason', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('approved_hours_or_expenses', models.FloatField(blank=True, null=True)),
                ('approval', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCost',
            fields=[
                ('googlesheetitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='googleSheetItem.GoogleSheetItem')),
                ('type_of_expenses', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('summary_of_costs', models.CharField(max_length=200)),
                ('amount_of_expenses_in_RON', models.FloatField(default=0)),
            ],
            bases=('googleSheetItem.googlesheetitem',),
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('googlesheetitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='googleSheetItem.GoogleSheetItem')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('number_of_extra_hours', models.IntegerField(default=0)),
                ('short_summary', models.CharField(max_length=500)),
                ('compensation_type', models.CharField(max_length=100)),
            ],
            bases=('googleSheetItem.googlesheetitem',),
        ),
    ]
